[project]
name = "wahl-kumpel"
version = "0.1.0"
description = "An assistant to answer urging questions on the parties running for German elections"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
